import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
const env = await initializeTestEnvironment({projectId:'demo-umt-adventure',database:{host:'127.0.0.1',port:9000,rules:readFileSync('../../firebase/database.rules.json','utf8')}});
const host = env.authenticatedContext('host').database();
const a = env.authenticatedContext('alice').database();
const b = env.authenticatedContext('bob').database();
const anon = env.unauthenticatedContext().database();
const path = 'rooms/ABC234';
const run = () => ({score:0,checkpoint:0,correct:0,wrong:0,elapsedMs:0,gems:0,finished:false,progress:0});
const player = name => ({nickname:name,avatar:0,round:0,connected:true,run:run()});
try {
 await env.clearDatabase();
 await assertFails(anon.ref(path).get());
 await assertSucceeds(host.ref(path).set({metadata:{hostId:'host',level:1,round:0,phase:'lobby',locked:false,startAt:0,pausedAt:0,pausedMs:0,expiresAt:Date.now()+21600000}}));
 await assertFails(a.ref(path+'/metadata/phase').set('playing'));
 await assertFails(a.ref(path+'/metadata/level').set(5));
 await assertSucceeds(a.ref(path+'/names/alice').set('alice'));
 await assertFails(b.ref(path+'/names/alice').set('bob'));
 await assertSucceeds(a.ref(path+'/players/alice').set(player('Alice')));
 await assertSucceeds(b.ref(path+'/names/bob').set('bob'));
 await assertSucceeds(b.ref(path+'/players/bob').set(player('Bob')));
 await assertFails(a.ref(path+'/players/bob/run/score').set(100));
 await assertFails(a.ref(path+'/players/alice/nickname').set('Bob'));
 await assertFails(a.ref(path+'/players/alice/run/score').set(100));
 await assertSucceeds(host.ref(path+'/metadata').update({phase:'countdown',startAt:Date.now()-5000,locked:true}));
 const late = env.authenticatedContext('late').database();
 await assertFails(late.ref(path+'/names/late').set('late'));
 const progress = {...run(),score:130,checkpoint:1,correct:1,elapsedMs:5000,progress:.1,topics:{'1':{correct:1}}};
 await assertSucceeds(a.ref(path+'/players/alice/run').set(progress));
 await assertFails(a.ref(path+'/players/alice/run/score').set(99999));
 await assertFails(a.ref(path+'/players/alice/run/progress').set(1.5));
 await assertFails(a.ref(path+'/players/alice/run').update({finished:true,progress:1}));
 await assertSucceeds(host.ref(path+'/metadata/phase').set('paused'));
 await assertFails(a.ref(path+'/players/alice/run/elapsedMs').set(6000));
 await assertSucceeds(a.ref(path+'/players/alice/connected').set(false));
 await assertSucceeds(host.ref(path).update({'metadata/round':1,'metadata/phase':'lobby','metadata/locked':false,'players/alice':{...player('Alice'),round:1},'players/bob':{...player('Bob'),round:1}}));
 await assertFails(a.ref(path+'/players/alice').update({round:0,run:progress}));
 await assertSucceeds(host.ref(path).update({'players/alice':null,'blocked/alice':true,'names/alice':null}));
 await assertFails(a.ref(path+'/names/alice').set('alice'));
 await assertFails(a.ref(path+'/players/alice').set({...player('Alice'),round:1}));
 assert.equal((await host.ref(path+'/players').get()).numChildren(),1);
 // Fifty separate authenticated clients, simultaneous progress updates.
 const clients = Array.from({length:49},(_,i)=>env.authenticatedContext(`p${i}`).database());
 await Promise.all(clients.map(async(db,i)=>{
   await assertSucceeds(db.ref(`${path}/names/student ${i}`).set(`p${i}`));
   await assertSucceeds(db.ref(`${path}/players/p${i}`).set({...player(`Student ${i}`),round:1}));
 }));
 assert.equal((await host.ref(path+'/players').get()).numChildren(),50);
 await host.ref(path+'/metadata').update({phase:'playing',startAt:Date.now()-5000,locked:true});
 await Promise.all(clients.map((db,i)=>assertSucceeds(db.ref(`${path}/players/p${i}/run`).set(progress))));
 await assertSucceeds(host.ref(path+'/metadata/phase').set('results'));
 await assertFails(b.ref(path).remove());
 await assertSucceeds(host.ref(path).remove());
 console.log('PASS: Firebase room permissions, lifecycle, recovery and 50 concurrent player writes.');
} finally { await env.cleanup(); }
